name: Update Parent Repository on Push

on:
  push:
    branches:
      - main

jobs:
  update-parent:
    uses: xcena-dev/.github/.github/workflows/submodule-update.yml@main
    with:
        parent_repository: 'xcena-dev/sdk_release'
        checkout_branch: 'main'
        submodule_path: 'driver/mxdriver'
        submodule_branch: 'main'
    secrets:
        PAT_TOKEN: ${{ secrets.METISX_GIT_ACTION_ACCESS_TOKEN }}
